### ISSUE TITLE
make data fails in geoclaw/examples/multi-layer/plane_wave

### ISSUE THREAD

**Issue by rjleveque** [clawpack/clawutil#146]
@mandli or @bolliger32, could you take a look at this?

Doing `make data` fails for me on the current master branch of geoclaw in the directory
`$CLAW/geoclaw/examples/multi-layer/plane_wave` 
with the error:

```
Traceback (most recent call last):
  File "/Users/rjl/git/clawpack/clawpack/clawutil/data.py", line 532, in write
    fname = signature(data_object.write).parameters['out_file'].default
KeyError: 'out_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setrun.py", line 521, in <module>
    rundata.write()
  File "/Users/rjl/git/clawpack/clawpack/clawutil/data.py", line 534, in write
    raise ValueError(type(data_object))
ValueError: <class '__main__.QinitMultilayerData'>
```

As far as I can tell this worked before 50b31ce79 in clawutil and not afterwards, including in the v5.6.1 release.

**Comment by mandli** [comment]
Yup, I ran into this earlier and have a fix that I should have pushed last week when I fixed it.  Has to do with the data object in there not having a default name when we look for it.

**Comment by bolliger32** [comment]
Ah! I was scratching my head about this one. Thanks @mandli !

**Comment by mandli** [comment]
It has to do with the new introspection we do on the data objects that breaks (the key associated with the file name is missing).

**Comment by rjleveque** [comment]
Thanks, now fixed.
